baseURL = 'https://ymorgil.github.io/web/'
locale = 'es'
title = 'My New Hugo Project'
theme = "hugo-book"

[[menus.after]]
name = "Mi otro repo"
url = "https://github.com/ymorgil/asir-add"
weight = 1